### ISSUE TITLE
Server overloaded?

### ISSUE THREAD

**Issue by skjerns** [perslev/U-Sleep-API-Python-Bindings#1]
Great that you supply even an API! Thanks alot!

However, I repeatedly get a server error, even though the website itself seems to work and manual upload/predict as well

```html
USleepAPI:Server response to POST: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. 
Either the server is overloaded or there is an error in the application.</p>
```

I get this error with the sample script when setting the model, or uploading a file

```Python
    api_token = "xxxxx"  # Insert here

    # Create an API object and (optionally) a new session.
    api = USleepAPI(api_token=api_token) # auth works fine!
    session = api.new_session(session_name="my_session")

    # See a list of valid models and set which model to use
    logger.info(f"Available models: {session.get_model_names()}")
    session.set_model("U-Sleep v1.0")
    # server error 500
```

Is this a programming error or is the server really overloaded?

**Comment by perslev** [comment]
Hi skjerns,

No, this seems to be an error, Ill have a look at it ASAP.

**Comment by perslev** [comment]
It seems there were two unrelated issues. One was indeed an internal server problem related to session names (they were enforced to be very short by mistake).

As for the file upload endpoint, is this working for you now? The server responded with an unexpected EDF header loading error (from the MNE package, see https://mne.tools/stable/generated/mne.io.read_raw_edf.html). If you still encounter the issue, could you please try and load your file using this function locally to see if you experience the same issue?

**Comment by skjerns** [comment]
everthing seems to work now! thanks for the lightning-fast response :)
